name: Example composite action
description: This is an example of creating composite action

inputs:
  appName:
    description: your docker app name
    required: true
  buildArtifactName:
    description: your build artifact
    required: true
outputs:
  greeting:
    description: your greeting sentence
    value: ${{ steps.say-hello.outputs.greeting }}
runs:
  using: "composite"
  steps:
    - name: Prepare Image tags
      id: image-tags
      shell: bash
      run: |
        base="${CONTAINER_IMAGE_URL}"
        tags="${base}:latest"

        if [[ '${{ github.ref }}' == *"refs/tags/"* ]]; then
        github_tag=$(echo "${GITHUB_REF#refs/*/}" | sed 's/^v//')
        tags=$(cat <<END_HEREDOC
        ${base}:${github_tag}
        ${base}:latest
        END_HEREDOC
        )
        elif [[ '${{ github.event_name }}' == 'push' ]]; then
          tags=$(cat <<END_HEREDOC
        ${base}:$(git rev-parse --short HEAD)
        ${base}:latest
        END_HEREDOC
          )
        elif [[ '${{ github.event_name }}' == 'pull_request' ]]; then
          tags=$(cat <<END_HEREDOC      
        ${base}:$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
        ${base}:pr-${{ github.event.number }}
        END_HEREDOC
          )
        fi

        echo "[INFO] tags: ${tags}"

        echo "IMAGE_TAGS<<EOF" >> $GITHUB_ENV
        echo "$tags" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.buildArtifactName }}

    - name: Set up Docker Buildx for building docker images
      uses: docker/setup-buildx-action@v1

    - name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: ${{ env.IMAGE_TAGS }}
